set gem install console to 1.19.0 (#379)
we need to set console to 1.19.0 to fix docker build issue failing at:

gem install async-http -v 0.54.0

due to:

ERROR:  Error installing async-http:
	The last version of console (~> 1.10) to support your Ruby & RubyGems was 1.19.0. Try installing it with `gem install console -v 1.19.0` and then running the current command again
	console requires Ruby version >= 3.0. The current ruby version is 2.7.6.219.