Pin to Python 3.8 to fix scapy error caused by removed tostring() method
Specifically this:

    • Failure in Spec Setup (BeforeEach) [7.522 seconds]
    DNS Policy with server on host
    /go/src/github.com/projectcalico/felix/fv/dns_scapy_test.go:558
      DNS response processing [BeforeEach]
      /go/src/github.com/projectcalico/felix/fv/dns_scapy_test.go:654
        A record
        /go/src/github.com/projectcalico/felix/fv/dns_scapy_test.go:662

        Container scapy-23256-288-felixfv failed before being listed in 'docker ps'
        Expected
            <chan struct {} | len:0, cap:0>: 0xc008d15980
        to be open

        /go/src/github.com/projectcalico/felix/fv/containers/containers.go:541

    scapy-23256-288-felixfv[stderr] Traceback (most recent call last):
    scapy-23256-288-felixfv[stderr]   File "/usr/local/bin/scapy", line 25, in <module>
    scapy-23256-288-felixfv[stderr]     interact()
    scapy-23256-288-felixfv[stderr]   File "/usr/local/lib/python3.9/site-packages/scapy/main.py", line 421, in interact
    scapy-23256-288-felixfv[stderr]     init_session(session_name, mydict)
    scapy-23256-288-felixfv[stderr]   File "/usr/local/lib/python3.9/site-packages/scapy/main.py", line 295, in init_session
    scapy-23256-288-felixfv[stderr]     scapy_builtins = {k: v for k, v in six.iteritems(importlib.import_module(".all", "scapy").__dict__) if _validate_local(k)}
    scapy-23256-288-felixfv[stderr]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    scapy-23256-288-felixfv[stderr]     return _bootstrap._gcd_import(name[level:], package, level)
    scapy-23256-288-felixfv[stderr]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    scapy-23256-288-felixfv[stderr]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    scapy-23256-288-felixfv[stderr]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    scapy-23256-288-felixfv[stderr]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    scapy-23256-288-felixfv[stderr]   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
    scapy-23256-288-felixfv[stderr]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    scapy-23256-288-felixfv[stderr]   File "/usr/local/lib/python3.9/site-packages/scapy/all.py", line 25, in <module>
    scapy-23256-288-felixfv[stderr]     from scapy.route import *
    scapy-23256-288-felixfv[stderr]   File "/usr/local/lib/python3.9/site-packages/scapy/route.py", line 191, in <module>
    scapy-23256-288-felixfv[stderr]     conf.route=Route()
    scapy-23256-288-felixfv[stderr]   File "/usr/local/lib/python3.9/site-packages/scapy/route.py", line 27, in __init__
    scapy-23256-288-felixfv[stderr]     self.resync()
    scapy-23256-288-felixfv[stderr]   File "/usr/local/lib/python3.9/site-packages/scapy/route.py", line 36, in resync
    scapy-23256-288-felixfv[stderr]     self.routes = read_routes()
    scapy-23256-288-felixfv[stderr]   File "/usr/local/lib/python3.9/site-packages/scapy/arch/linux.py", line 280, in read_routes
    scapy-23256-288-felixfv[stderr]     tmp_route = get_alias_address(iff, dst_int, gw_str, metric)
    scapy-23256-288-felixfv[stderr]   File "/usr/local/lib/python3.9/site-packages/scapy/arch/linux.py", line 195, in get_alias_address
    scapy-23256-288-felixfv[stderr]     names = names.tostring()
    scapy-23256-288-felixfv[stderr] AttributeError: 'array.array' object has no attribute 'tostring'