More debugging for traceroute problem
Which is this:

    2021-03-02 15:38:02,860 INFO run: kubectl exec client -n dualtor -- timeout 5s traceroute -n 10.244.82.21
    2021-03-02 15:38:02,921 INFO rc 1 output:
    error: unable to upgrade connection: container not found ("client")

    For some reason, running ServiceIP failover test (without tor2tor, tor2node), traceroute could get into the the state that it lost packets on last test case. Print log for now and retry with longer timeout. We will debug it later.
    2021-03-02 15:38:02,922 INFO run: kubectl exec client -n dualtor -- timeout 25s traceroute -n 10.244.82.21
    2021-03-02 15:38:02,986 INFO rc 1 output:
    error: unable to upgrade connection: container not found ("client")

This happens almost immediately after a successful "kubectl exec
client -n dualtor -- date", so it's a mystery what the real issue is
here.