make update-libcalico
Then manually edited to avoid netlink and x/sys bumps, as that causes these errors:

vendor/github.com/vishvananda/netlink/bridge_linux.go:22:27: undefined: unix.IFLA_EXT_MASK
vendor/github.com/vishvananda/netlink/bridge_linux.go:38:9: undefined: unix.IFLA_AF_SPEC
vendor/github.com/vishvananda/netlink/bridge_linux.go:90:21: undefined: unix.IFLA_AF_SPEC
vendor/github.com/vishvananda/netlink/link_linux.go:380:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:410:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:440:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:471:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:505:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:552:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:676:23: undefined: unix.IFLA_NET_NS_FD
vendor/github.com/vishvananda/netlink/link_linux.go:676:23: too many errors