create-test-vm: Retry apt-get update step up to 3 times (in total)
We sometimes see apt-get failing like this:

    Get:42 http://security.ubuntu.com/ubuntu focal-security/multiverse Translation-en [4,316 B]
    Get:43 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 c-n-f Metadata [528 B]
    Fetched 19.1 MB in 4s (4,894 kB/s)
    Traceback (most recent call last):
      File "/usr/lib/cnf-update-db", line 26, in <module>
        col.create(db)
      File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 100, in create
        json.dump(self._calc_input_metadata(), fp)
      File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 114, in _calc_input_metadata
        st = os.stat(p)
    FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_focal-backports_universe_cnf_Commands-amd64'
    Reading package lists... Done
    E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
    E: Sub-process returned an error code

Don't really know why.
https://groups.google.com/g/gce-discussion/c/40x7iYAfCQ4 suggests it
could be conflict with another package update process that runs
automatically shortly after instance creation.  But that's just a
guess.  Let's see if retrying helps.